# Destination Path for exporting the data
#DES="/mnt/nas"

# USB Drive Storage Information
#IMG_FILE="/mnt/storage/drive.img"
#STORAGE_SIZE="16G"

# USB Hardware Information
#SN="1234567890"
#MFG="Raspberry Pi"
#PRODUCT="usb-to-nas"

